// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/hostproto/host.proto

package hostproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's message.
type HostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_hostproto_host_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_hostproto_host_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) {
	return file_cmd_hostproto_host_proto_rawDescGZIP(), []int{0}
}

func (x *HostRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the original message.
type HostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HostReply) Reset() {
	*x = HostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_hostproto_host_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostReply) ProtoMessage() {}

func (x *HostReply) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_hostproto_host_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostReply.ProtoReflect.Descriptor instead.
func (*HostReply) Descriptor() ([]byte, []int) {
	return file_cmd_hostproto_host_proto_rawDescGZIP(), []int{1}
}

func (x *HostReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cmd_hostproto_host_proto protoreflect.FileDescriptor

var file_cmd_hostproto_host_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6d, 0x64, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x6f, 0x73, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25,
	0x0a, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x42, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x3a, 0x0a,
	0x08, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x77, 0x61, 0x74,
	0x65, 0x72, 0x2f, 0x73, 0x74, 0x64, 0x69, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6d, 0x64,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cmd_hostproto_host_proto_rawDescOnce sync.Once
	file_cmd_hostproto_host_proto_rawDescData = file_cmd_hostproto_host_proto_rawDesc
)

func file_cmd_hostproto_host_proto_rawDescGZIP() []byte {
	file_cmd_hostproto_host_proto_rawDescOnce.Do(func() {
		file_cmd_hostproto_host_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_hostproto_host_proto_rawDescData)
	})
	return file_cmd_hostproto_host_proto_rawDescData
}

var file_cmd_hostproto_host_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_hostproto_host_proto_goTypes = []interface{}{
	(*HostRequest)(nil), // 0: hostproto.HostRequest
	(*HostReply)(nil),   // 1: hostproto.HostReply
}
var file_cmd_hostproto_host_proto_depIdxs = []int32{
	0, // 0: hostproto.Host.CallHost:input_type -> hostproto.HostRequest
	1, // 1: hostproto.Host.CallHost:output_type -> hostproto.HostReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_hostproto_host_proto_init() }
func file_cmd_hostproto_host_proto_init() {
	if File_cmd_hostproto_host_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_hostproto_host_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_hostproto_host_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_hostproto_host_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_hostproto_host_proto_goTypes,
		DependencyIndexes: file_cmd_hostproto_host_proto_depIdxs,
		MessageInfos:      file_cmd_hostproto_host_proto_msgTypes,
	}.Build()
	File_cmd_hostproto_host_proto = out.File
	file_cmd_hostproto_host_proto_rawDesc = nil
	file_cmd_hostproto_host_proto_goTypes = nil
	file_cmd_hostproto_host_proto_depIdxs = nil
}
